// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/DenisBarabanshchikov/subscription/config"
	"github.com/DenisBarabanshchikov/subscription/internal/adapter/payment_povider/stripe"
	"github.com/DenisBarabanshchikov/subscription/internal/adapter/subscription"
	"github.com/DenisBarabanshchikov/subscription/internal/handler/http"
	"github.com/DenisBarabanshchikov/subscription/internal/port"
	"github.com/DenisBarabanshchikov/subscription/internal/service"
	"github.com/google/wire"
	"github.com/stripe/stripe-go/v74/client"
)

// Injectors from wire.go:

func subscriptionRepository(config subscription.DynamoConfig) subscription.Repository {
	repository := subscription.NewDynamoRepository(config)
	return repository
}

func stripeApi(client2 *client.API) stripe.Api {
	api2 := stripe.NewApi(client2)
	return api2
}

func subscriptionPort(repository subscription.Repository) port.Subscription {
	portSubscription := subscription.NewAdapter(repository)
	return portSubscription
}

func paymentProviderPort(api2 stripe.Api) port.PaymentProvider {
	paymentProvider := stripe.NewAdapter(api2)
	return paymentProvider
}

func InitializeHandlers() (*http.Handlers, error) {
	dynamoConfig := config.ProvideSubscriptionDynamoConfig()
	repository := subscriptionRepository(dynamoConfig)
	portSubscription := subscriptionPort(repository)
	clientAPI := config.ProvideStripeClient()
	api2 := stripeApi(clientAPI)
	paymentProvider := paymentProviderPort(api2)
	subscriptionService := service.NewSubscriptionService(portSubscription, paymentProvider)
	subscriptionHandler := http.NewSubscriptionHandler(subscriptionService)
	handlers := http.NewHandlers(subscriptionHandler)
	return handlers, nil
}

// wire.go:

var configs = wire.NewSet(config.ProvideSubscriptionDynamoConfig)

var clients = wire.NewSet(config.ProvideStripeClient)

var repositories = wire.NewSet(
	subscriptionRepository,
)

var api = wire.NewSet(
	stripeApi,
)

var ports = wire.NewSet(
	subscriptionPort,
	paymentProviderPort,
)
