definitions:
  request.CreateCustomer:
    properties:
      email:
        type: string
    type: object
  request.SubscribeCustomer:
    properties:
      plan:
        type: string
    type: object
  response.CreateCustomer:
    properties:
      customerId:
        type: string
      externalCustomerId:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  response.SubscribeCustomer:
    properties:
      externalSubscriptionId:
        type: string
      subscriptionId:
        type: string
    type: object
  response.SubscriptionStatus:
    properties:
      externalSubscriptionId:
        type: string
      plan:
        type: string
      status:
        type: string
      subscriptionId:
        type: string
    type: object
info:
  contact: {}
  description: This is the API documentation for the subscription service.
  title: Subscription Service API Documentation
  version: 1.0.0
paths:
  /api/v1/customers:
    post:
      consumes:
      - application/json
      description: Creating a new customer
      parameters:
      - description: Customer data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateCustomer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CreateCustomer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Customer
  /api/v1/customers/{customerId}/subscriptions:
    post:
      consumes:
      - application/json
      description: 'Subscribe a customer (Available plans: Core, Growth, Premium)'
      parameters:
      - description: customerId
        in: path
        name: customerId
        required: true
        type: string
      - description: Subscription data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.SubscribeCustomer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SubscribeCustomer'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Customer
  /api/v1/customers/{customerId}/subscriptions/{subscriptionId}:
    get:
      consumes:
      - application/json
      description: Get subscription status
      parameters:
      - description: customerId
        in: path
        name: customerId
        required: true
        type: string
      - description: subscriptionId
        in: path
        name: subscriptionId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SubscriptionStatus'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Customer
  /api/v1/stripe/webhook:
    post:
      consumes:
      - application/json
      description: Handles the stripe webhook
      produces:
      - application/json
      responses:
        "202":
          description: Accepted - no content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      tags:
      - Stripe
swagger: "2.0"
